package com.vsrstudio.dict

val WORDS = listOf(
        "It is also assumed that" to "Предполагается также, что",
        "be subject to smth" to "Подвергаться чему-либо, быть предметом чего-то",
        "In this framework, (they examine)" to "В этих рамках/системе/фреймворке (они изучают/исследуют)",
        "To get some idea about how …." to "Чтобы получить некоторое представление о том, как ....",
        "Proposal" to "Предложение, заявка, рекомендация",
        "To propose" to "Предложить",
        "To denote / encode" to "Для обозначения / кодирования",
        "(Their) contribution is threefold." to "Их вклад тройной/трёхкратный",
        "To exploit" to "Использовать, пользоваться, эксплуатировать",
        "To provide a new insight into // to provide new insights into" to "Чтобы обеспечить/предоставить новый взгляд/понимание/идею о",
        "To validate the approach" to "Для проверки подхода",
        "To carry out / to conduct a study / a research / an investigation" to "Провести изучение/исследование/расследование учения/исследования/расследования",
        "To take into account" to "Учитывать, брать в расчёт",
        "The aim is to… so as to…" to "Цель состоит в том, чтобы... чтобы...",
        "Objects under study" to "Рассматриваемые объекты",
        "We start with a short introduction into…" to "Мы начнем с краткого введения в...",
        "Section 3 describes the work still to be done // They describe the work still to be done." to "Раздел 3 описывает работу которую еще предстоит сделать // они описывают работу, которую еще предстоит сделать.",
        "In words, …" to "На словах, ...",
        "To make precise the scope of the study / analysis" to "Чтобы уточнить рамки исследования / анализа",
        "To flesh this out, they give an example (it is necessary to give an example)" to "Чтобы конкретизировать это, они приводят пример (необходимо привести пример)",
        "Conversely,…" to "Наоборот, напротив",
        "The authors trace back the problem of … // Smth can be traced back to…" to "Авторы проследили проблему // Что-то может быть прослежено до...",
        "findings / results" to "Выводы / результаты",
        "Game theory was pioneered by Princeton mathematician John von Neumann." to "Теория игр была впервые введена Принстонским математиком Джоном фон Нейманом.",
        "Today, game theory applies to a wide range of behavioral relations, and is now an umbrella term for the science of logical decision making in humans, animals, and computers." to "Сегодня теория игр применяется в широком спектре поведенческих отношений, и теперь является общим термином для науки логического принятия решений людьми, животными и компьютерами.",
        "By A we shall (basically) understand B = By A we (basically) understand / mean B = With A, we mean B" to "Под А мы будем (в основном) понимать Б = Под А мы (в основном) понимаем/имеем в виду Б = Под А мы имеем в виду Б",
        "Researchers have been actively investigating the problem of…" to "Исследователи активно изучают проблему...",
        "Recent years have seen rapid growth of / in …" to "В последние годы наблюдается стремительный рост (области) / в (чём-то)...",
        "A challenging aspect of this problem that seems to distinguish it from … is that …" to "Сложный аспект этой задачи, который отличает её от ... это ...",
        "Another, more related area of research is that of (determining…)" to "Другая, более связанная/похожая/родственная область исследований - это (определение ...)",
        "To avoid domination of the corpus by a small number of active reviewers, we imposed a limit of fewer that 20 reviews per author" to "Чтобы избежать доминирования корпуса небольшого количества активных рецензентов, мы ввели ограничение - не больше 20 комментариев от одного автора",
        "As it turns out, …" to "Как выясняется/как оказалось",
        "to utilize" to "использовать/задействовать/применить",
        "apart from" to "кроме/помимо/наряду с",
        "subject matter" to "Сущность/вещество/материя предмета",
        "to yield" to "уступать/сдаваться/производить",
        "plausible" to "правдоподобно/вероятно/достоверно",
        "so that (the result would be 50%)" to "так что (результат будет 50%)",
        "to suffice" to "хватать, быть достаточным, хватить, удовлетворять",
        "account for: \n~ What accounts for these two differences? \n~ Gazprom accounts for 90% of the Russian GDP." to "можно объяснить, составлять: \n~ Чем можно объяснить эти два отличия? \n~ Газпрома составляет 90% ВВП России."
)